name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:
    env:
      USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      PASSWORD: ${{ secrets.REGISTRY_PASSOWORD }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker login -u $USERNAME -p $PASSWORD
        docker build . --file Dockerfile --tag tiagomatana/nginx:latest
        docker push tiagomatana/nginx:latest
